"use client";import{useEffect as N,useRef as p,useState as b,useCallback as y}from"react";import{useRouter as A}from"next/navigation";import{getSupabaseBrowserClient as L}from"@/lib/supabase/client";import{useAuth as R}from"@/lib/auth-context";const S=["AL","AK","AS","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"];export default function E(){const o=L(),m=A(),{college:u}=R(),h=p(null),s=p(null),c=p(null),[r,w]=b(""),[C,k]=b(0),f=y(async()=>{if(!u?.id)return[];const{data:e}=await o.from("watchlist_items").select("school_id").eq("college_id",u.id);return(e||[]).map(l=>l.school_id)},[o,u]),g=y(async()=>{const e=(await import("leaflet")).default;await import("leaflet.markercluster");let l=o.from("schools").select("id,name,city,state,hc_first_name,hc_last_name,lat,lon").not("lat","is",null).limit(3e3);r&&(l=l.eq("state",r));const{data:a}=await l,M=await f();if(s.current||(s.current=e.map(h.current).setView([39.5,-98.35],4),e.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors",maxZoom:18}).addTo(s.current),c.current=e.markerClusterGroup({maxClusterRadius:45}),s.current.addLayer(c.current)),c.current.clearLayers(),(a||[]).forEach(t=>{const d=M.includes(t.id)?"#d4a017":"#697386",n=e.circleMarker([t.lat,t.lon],{radius:6,color:d,fillColor:d,fillOpacity:.85,weight:1}),i=document.createElement("div");i.innerHTML=`<strong>${t.name}</strong><br/>${t.city}, ${t.state}<br/>HC: ${t.hc_first_name||""} ${t.hc_last_name||""}<br/><button id="view-${t.id}" style="margin-top:6px;cursor:pointer">View profile</button>`,n.bindPopup(i),n.on("popupopen",()=>{const v=document.getElementById(`view-${t.id}`);v&&(v.onclick=()=>m.push(`/schools/${t.id}`))}),c.current.addLayer(n)}),k((a||[]).length),r&&a?.length){const t=a.reduce((n,i)=>n+i.lat,0)/a.length,d=a.reduce((n,i)=>n+i.lon,0)/a.length;s.current.setView([t,d],6)}else s.current.setView([39.5,-98.35],4)},[o,r,f,m]);return N(()=>{if(!document.getElementById("leaflet-css")){const e=document.createElement("link");e.id="leaflet-css",e.rel="stylesheet",e.href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css",document.head.appendChild(e);const l=document.createElement("link");l.rel="stylesheet",l.href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.css",document.head.appendChild(l);const a=document.createElement("link");a.rel="stylesheet",a.href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.Default.css",document.head.appendChild(a)}g()},[g]),<div className="view">
      <div className="view-header"><div><h1>Recruiting Territory Map</h1><p>Live map of the national database — {C.toLocaleString()} schools in view</p></div></div>
      <div className="filters">
        <div className="field">
          <label>State</label>
          <select value={r}onChange={e=>w(e.target.value)}>
            <option value="">All states</option>
            {S.map(e=><option key={e}value={e}>{e}</option>)}
          </select>
        </div>
        <div className="field"><label>&nbsp;</label><div style={{fontSize:12,color:"#697386",display:"flex",gap:12,alignItems:"center"}}>
          <span><span style={{display:"inline-block",width:10,height:10,borderRadius:"50%",background:"#d4a017",marginRight:4}}/>Watchlisted</span>
          <span><span style={{display:"inline-block",width:10,height:10,borderRadius:"50%",background:"#697386",marginRight:4}}/>Not watchlisted</span>
        </div></div>
      </div>
      <div id="leaflet-map"ref={h}/>
    </div>}